# Buil cofiguration for Lily58 split keyboard with nice!nano controllers.
# This buils separate UF2 files for the left and right halves.

# board: [ "nice_nano" ]
# shield: [ "lily58_left", "lily58_right" ]

include:
  - board: nice_nano_v2
    shield: lily58_left
  - board: nice_nano_v2
    shield: lily58_right
  - board: nice_nano_v2
    shield: settings_reset
